# Generated by Django 5.0.7 on 2024-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ad_id', models.IntegerField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('views_count', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
